package uk.co.llblumire.cs2ja16.week2;

/**
 * Outputs a multiplication table to stdout
 * 
 * @author L. L. Blumire
 *
 */
public class MultiplicationTable {
	
	/**
	 * Stores the number to generate the table up to including 
	 */
	int maxNum;
	
	/**
	 * Stores the data generated by getResult 
	 */
	int[][] tableData;
	
	/**
	 * Constructor for MultiplicationTable
	 * @param maxNum the size of the table to generate
	 */
	public MultiplicationTable(int maxNum) {
		this.maxNum = maxNum;
		this.tableData = new int[maxNum][maxNum];
	}
	
	/**
	 * Generates the multiplication table
	 * @return A string formatted version of the table, tab aligned
	 */
	String getResult() {
		String res = new String();
		
		for (int y = 0; y < this.maxNum; ++y) {
			for (int x = 0; x < this.maxNum; ++x) {
				this.tableData[y][x] = (y + 1) * (x + 1);
				res += this.tableData[y][x];
				res += "\t";
			}
			res += "\n";
		}
		
		return res;
	}
	
	/**
	 * Prints a 10 times table
	 */
	public static void main(String[] args) {
		MultiplicationTable mt = new MultiplicationTable(10);
		System.out.println(mt.getResult());
	}

}
